model:
  class_path: synthmap.task.SynthMapTask
  init_args:
    param_encoder: models/param_encoder_mlp.yaml
    param_decoder: models/param_decoder_mlp.yaml
    bottleneck:
      class_path: synthmap.models.autoencoder.GaussianVAE
      init_args:
        beta: 0.01
    loss_fn: torch.nn.CrossEntropyLoss
    param_discretizer:
      class_path: synthmap.params.DiscretizedNumericalParameters
      init_args:
        num_params: 14
        steps_per_param: 32
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
data: data/genetic.yaml
trainer:
  devices: 1
  accelerator: gpu
  max_epochs: 250
seed_everything: 3608013887
