model:
  class_path: synthmap.task.SynthMapTask
  init_args:
    param_encoder: models/param_encoder_mlp.yaml
    param_decoder: models/param_decoder_mlp.yaml
    bottleneck:
      class_path: synthmap.models.autoencoder.GaussianVAE
      init_args:
        beta: 0.01
    loss_fn: loss/mae_mse_loss.yaml
    audio_regularizer: loss/timbre_regularizer.yaml
    audio_regularizer_weight: 0.05
    # param_discretizer:
    #   class_path: synthmap.params.DiscretizedNumericalParameters
    #   init_args:
    #     num_params: 14
    #     steps_per_param: 32
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0001
data: data/genetic.yaml
trainer:
  devices: 1
  accelerator: gpu
  max_epochs: 250
  callbacks:
  - class_path: synthmap.callback.SaveAudioCallback
seed_everything: 3608013887
