model:
  class_path: synthmap.task.SynthMapTask
  init_args:
    audio_encoder: models/soundstream_encoder.yaml
    param_decoder: models/transformer_encoder.yaml
    loss_fn: torch.nn.MSELoss
    # param_discretizer:
    #   class_path: synthmap.params.DiscretizedNumericalParameters
    #   init_args:
    #     num_params: 14
    #     steps_per_param: 32
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0001
data: data/gpu_808.yaml
trainer:
  devices: 1
  accelerator: gpu
  max_epochs: 250
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: synthmap
      name: soundmatch_transformer_1M
      save_dir: ./lightning_logs
      log_model: false
    dict_kwargs:
      job_type: train
      group: synthmap
      entity: jordieshier
  # callbacks:
  # - class_path: lightning.pytorch.callbacks.BatchSizeFinder
seed_everything: 3608013887
