model:
  class_path: synthmap.task.SynthMapTask
  init_args:
    autoencoder: models/vae.yaml
    loss_fn: torch.nn.CrossEntropyLoss
    param_discretizer:
      class_path: synthmap.params.DiscretizedNumericalParameters
      init_args:
        num_params: 14
        steps_per_param: 32
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
data: data/snare_808.yaml
trainer:
  devices: 1
  accelerator: gpu
  # accelerator: cpu
  max_epochs: 250
  # callbacks:
  #   - class_path: torchdrum.callback.SaveAudioCallback
  #   - class_path: torchdrum.callback.SaveTorchScriptCallback
  #   - class_path: lightning.pytorch.callbacks.LearningRateMonitor
  #     init_args:
  #       logging_interval: step
seed_everything: 3608013887
